apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: har1
  namespace: vela-system
spec:
  components:
  - name: har1-hihar-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 20Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
status: {}
