apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 0746aafcad8a4dafc318cabdd33834ad8de5aafe
  application.deploy.reform/deploymentNo: har2-dev-approval_DP1
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: har2
  application.deploy.reform/repository: https://github.com/Gglayolun/harrisrepo.git
  application.deploy.reform/repositoryPath: har2
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
