apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: harrisrepo
  namespace: vela-system
spec:
  components:
  - name: harrisrepo-harr1-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: docker
      imagePullPolicy: IfNotPresent
      memory: 21Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
status: {}
