apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 0e3e0ba62c606464427a83e99e306a2d18c2050f
  application.deploy.reform/deploymentNo: harrisrepo-dev-approval_DP2
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: harrisrepo
  application.deploy.reform/repository: https://github.com/Gglayolun/harrisrepo.git
  application.deploy.reform/repositoryPath: harrisrepo
  application.deploy.reform/revision: 2023.04.2
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
